services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - 6379:6379
  
  review-worker:
    build: .
    container_name: review-worker
    command: npm run start
    environment:
      - PORT=3000
      - APP_ID=${APP_ID}
      - GITHUB_APP_PRIVATE_KEY_PATH=${GITHUB_APP_PRIVATE_KEY_PATH}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENROUTER_MODEL=${OPENROUTER_MODEL}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "3000:3000"
    depends_on:
      - redis
    restart: unless-stopped